// Import: Node.js modules.
import {readFile, writeFile} from "node:fs/promises";

// Import: constants.
import {ERROR_TARGET_REASON_MAP} from "../dist/data/constants/ERROR_TARGET_REASON_MAP.mjs";

// File paths.
const inputFile = "./src/data/errors.json";
const outputFile = "./src/index.ts";

// Read and parse JSON.
const rawJson = await readFile(inputFile, "utf8");
const definitions = JSON.parse(rawJson);

/**
 * Generates a predefined error class based on the provided name and definition object.
 * The created class extends the `CustomBaseError` class and is designed for use with standardized error handling.
 *
 * @author  Roland Milto (https://roland.milto.de/)
 * @version 2026-03-28
 *
 * @param		{string} errorName	- The name of the error class to be created.
 * @param   {object} error  		- The definition object specifying error properties, including:
 *                         				- `code`: {string} Unique error code value.
 *                         				- `comment`: {string} JSDoc comment for the error class.
	 *                         			- `message`: {string} Default error message.
 *                         				- `reason`: {string} Error reason explanation.
 *                         				- `severity`: {string} Severity level of the error.
 *                         				- `target`: {string} Error target field or context.
 *
 * @returns {string}      			- The string representation of the generated class definition text.
 *
 * @throws  {TypeError}   			- If invalid argument types are provided.
 *
 * @example
 * // Simple predefined class creation
 * const name = 'InvalidDataError';
 * const def = {
 *   comment: 'Custom error for invalid data send to database..',
 *   code: 404,
 *   severity: 'critical',
 *   target: 'database',
 *   reason: 'query',
 *   message: 'The provided data is invalid.'
 * };
 * const result = _createPredefinedClass(name, def);
 * // 'class InvalidDataError extends CustomBaseError { ... }'
 */
function _createPredefinedClass(errorName, error)
{
	const jsDoc = _formatJsDoc(error.comment);

	return [
		jsDoc,
		`class ${errorName} extends CustomBaseError {`,
		`  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {`,
		`    super({ code: ${error.code}, severity: ${JSON.stringify(error.severity)}, message: ${JSON.stringify(error.message)}, ...options, reason: ${JSON.stringify(error.reason)}, target: ${JSON.stringify(error.target)}, isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);`,
		`  }`,
		`}`
	].join("\n");
}

/**
 * Formats a given comment string as a JSDoc-style comment block. Handles both single-line and multi-line comments.
 * The method ensures proper formatting with JSDoc syntax for easy readability and integration in documentation tools.

 * @author  Roland Milto (https://roland.milto.de/)
 * @version 2026-03-28

 * @param   {string}  comment  - The input comment string to be formatted as a JSDoc block.

 * @returns {string}           - The formatted JSDoc comment string.

 * @example
 * // Single-line comment example:
 * const formatted = _formatJsDoc("This is a test comment.");
 * // /** This is a test comment. */
function _formatJsDoc(comment)
{
	const lines = String(comment).split(/\r?\n/u);

	// Single-line comment.
	if (lines.length === 1) {
		return `/** ${lines[0]} */`;
	}

	// Multiline comments.
	return [
		"/**",
		...lines.map((line) => ` * ${line}`),
		" */"
	].join("\n");
}

// Check for valid target-reason combinations.
for (const [errorName, def] of Object.entries(definitions)) {
	if (!ERROR_TARGET_REASON_MAP[def.target]?.includes(def.reason)) {
		throw new Error(`Invalid reason "${def.reason}" for target "${def.target}" in ${errorName}. Update constant "/error/src/data/constants/ERROR_TARGET_REASON_MAP".`);
	}
}

// Sort keys to keep output stable.
const entries = Object.entries(definitions).sort(([leftName], [rightName]) =>
	leftName.localeCompare(rightName, "en")
);

// Build file content.
const chunks = [];

chunks.push(`// DO NOT EDIT: AUTOGENERATED FILE BY index.gen.mjs
/**
 * @package     @js-augment/error
 * @see         https://github.com/roland-milto/js-augment-error
 * @author      Roland Milto (https://roland.milto.de/)
 */
 
// Import: interfaces and types.
import type {CustomAdditionalErrorDetails} from "./types/CustomAdditionalErrorDetails.js";
import type {RequiredPredefinedErrorDetails} from "./types/RequiredPredefinedErrorDetails.js";

// Import: classes.
import {CustomBaseError} from "./classes/CustomBaseError.class.js";
`);

// Generate classes.
for (const [name, def] of entries) {
	chunks.push(_createPredefinedClass(name, def));
	chunks.push("");
}

// Export block at the end of the file.
chunks.push(`// Export custom error classes.
export {`);
chunks.push(entries.map(([name]) => `  ${name},`).join("\n"));
chunks.push(`};

// Export custom error generator function.
export {createCustomNamedError} from "./functions/createCustomNamedError.js";

// Export constants.
export {ERROR_TARGET_REASON_MAP} from "./data/constants/ERROR_TARGET_REASON_MAP.js";
export {SEVERITY} from "./data/constants/SEVERITY.js";

// Export: interfaces and types.
export type {CustomAdditionalErrorDetails} from "./types/CustomAdditionalErrorDetails.js";
export type {CustomBaseErrorOptions} from "./types/CustomBaseErrorOptions.js";
export type {DefaultErrorOptions} from "./types/DefaultErrorOptions.js";
export type {ErrorReason} from "./types/ErrorReason.js";
export type {ErrorTarget} from "./types/ErrorTarget.js";
export type {ErrorTargetReasonMap} from "./types/ErrorTargetReasonMap.js";
export type {RequiredPredefinedErrorDetails} from "./types/RequiredPredefinedErrorDetails.js";
export type {Severity} from "./types/Severity.js";`);


// Write output.
await writeFile(outputFile, chunks.join("\n"), "utf8");

console.log(`Generated ${outputFile}`);