// DO NOT EDIT: AUTOGENERATED FILE BY index.gen.mjs
/**
 * @package     @js-augment/error
 * @see         https://github.com/roland-milto/js-augment-error
 * @author      Roland Milto (https://roland.milto.de/)
 */
 
// Import: interfaces and types.
import type {CustomAdditionalErrorDetails} from "./types/CustomAdditionalErrorDetails.js";
import type {RequiredPredefinedErrorDetails} from "./types/RequiredPredefinedErrorDetails.js";

// Import: classes.
import {CustomBaseError} from "./classes/CustomBaseError.class.js";

/** Thrown when an API request is malformed or contains invalid parameters. */
class ApiInvalidRequestError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Invalid API request.", ...options, reason: "request", target: "api", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the API endpoint does not support the requested HTTP method. */
class ApiMethodNotAllowedError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 405, severity: "error", message: "The API method is not allowed.", ...options, reason: "request", target: "api", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the requested API endpoint or resource does not exist. */
class ApiNotFoundError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 404, severity: "error", message: "API resource not found.", ...options, reason: "notFound", target: "api", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the API request rate limit has been exceeded. */
class ApiRateLimitError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 429, severity: "error", message: "API rate limit exceeded.", ...options, reason: "limit", target: "api", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the requested API version is invalid or unsupported. */
class ApiVersionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Invalid API version.", ...options, reason: "request", target: "api", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an assertion in the code fails. */
class AssertionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "Assertion failed.", ...options, reason: "assertion", target: "other", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when access to a resource is explicitly forbidden. */
class AuthForbiddenError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 403, severity: "error", message: "Access is forbidden.", ...options, reason: "forbidden", target: "auth", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the authenticated user lacks the required permissions. */
class AuthPermissionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 403, severity: "error", message: "Permission denied.", ...options, reason: "permission", target: "auth", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an authentication session has expired and re-authentication is required. */
class AuthSessionExpiredError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 401, severity: "error", message: "Authentication session expired.", ...options, reason: "unauthorized", target: "auth", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when authentication is required but missing or invalid. */
class AuthUnauthorizedError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 401, severity: "error", message: "Authentication required.", ...options, reason: "unauthorized", target: "auth", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a connection to the database cannot be established. */
class DatabaseConnectionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 503, severity: "error", message: "Database connection failed.", ...options, reason: "connection", target: "database", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an existing database connection is unexpectedly lost. */
class DatabaseDisconnectionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 503, severity: "error", message: "Database connection was lost.", ...options, reason: "connection", target: "database", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a database query fails during execution. */
class DatabaseQueryError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 503, severity: "error", message: "Database query failed.", ...options, reason: "query", target: "database", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a database operation exceeds the allowed time limit. */
class DatabaseTimeoutError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 503, severity: "error", message: "Database operation timed out.", ...options, reason: "timeout", target: "database", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when attempting to create a directory that already exists. */
class DirectoryAlreadyExistsError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 409, severity: "error", message: "Directory already exists.", ...options, reason: "exists", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a directory cannot be created due to an operation failure. */
class DirectoryCreationError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 409, severity: "error", message: "Directory creation failed.", ...options, reason: "operation", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when deleting a directory fails during the operation. */
class DirectoryDeletionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 409, severity: "error", message: "Directory deletion failed.", ...options, reason: "operation", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a directory is unexpectedly empty. */
class DirectoryEmptyError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Directory is empty.", ...options, reason: "content", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a directory was expected but not provided or found. */
class DirectoryExpectedError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 422, severity: "error", message: "Directory was expected.", ...options, reason: "expected", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a directory is expected to be empty but contains files or subdirectories. */
class DirectoryNotEmptyError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 409, severity: "error", message: "Directory is not empty.", ...options, reason: "content", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a requested directory cannot be found. */
class DirectoryNotFoundError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 404, severity: "error", message: "Directory not found.", ...options, reason: "notFound", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a directory path does not match the expected format. */
class DirectoryPathFormatError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Directory path format is invalid.", ...options, reason: "format", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the current process lacks permission to access or modify a directory. */
class DirectoryPermissionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 403, severity: "error", message: "Directory permission denied.", ...options, reason: "permission", target: "directory", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when attempting to create a file that already exists. */
class FileAlreadyExistsError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 409, severity: "error", message: "File already exists.", ...options, reason: "exists", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when copying a file fails during the operation. */
class FileCopyError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 507, severity: "error", message: "File copy failed.", ...options, reason: "operation", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file cannot be created due to an operation failure. */
class FileCreationError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 409, severity: "error", message: "File creation failed.", ...options, reason: "operation", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when deleting a file fails during the operation. */
class FileDeletionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 409, severity: "error", message: "File deletion failed.", ...options, reason: "operation", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file is unexpectedly empty. */
class FileEmptyError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "File is empty.", ...options, reason: "content", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file was expected but not provided or found. */
class FileExpectedError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 422, severity: "error", message: "File was expected.", ...options, reason: "expected", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file has an invalid or unsupported extension or format. */
class FileExtensionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "File extension is invalid.", ...options, reason: "format", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a requested file cannot be found. */
class FileNotFoundError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 404, severity: "error", message: "File not found.", ...options, reason: "notFound", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file path does not match the expected format. */
class FilePathFormatError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "File path format is invalid.", ...options, reason: "format", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the current process lacks permission to access or modify a file. */
class FilePermissionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 403, severity: "error", message: "File permission denied.", ...options, reason: "permission", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file operation fails due to system-level limitations such as disk quotas or file system constraints. */
class FileSystemLimitError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 507, severity: "error", message: "File system limits exceeded.", ...options, reason: "system", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file cannot be read during an operation. */
class FileUnreadableError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 403, severity: "error", message: "File is unreadable.", ...options, reason: "operation", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file cannot be written during an operation. */
class FileUnwritableError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 403, severity: "error", message: "File is unwritable.", ...options, reason: "operation", target: "file", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a requested link or symbolic link cannot be found. */
class LinkNotFoundError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 404, severity: "error", message: "Link not found.", ...options, reason: "notFound", target: "link", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a network address is already in use by another process. */
class NetworkAddressInUseError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "Network address is already in use.", ...options, reason: "used", target: "network", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a network connection cannot be established or fails unexpectedly. */
class NetworkConnectionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "Network connection failed.", ...options, reason: "connection", target: "network", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the target host cannot be reached over the network. */
class NetworkHostUnreachableError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "Network host is unreachable.", ...options, reason: "host", target: "network", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a network port is already in use by another process. */
class NetworkPortInUseError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "Network port is already in use.", ...options, reason: "used", target: "network", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an expected property is missing from an object. */
class ObjectPropertyMissingError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Required object property is missing.", ...options, reason: "property", target: "object", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a file system path exceeds the maximum allowed length. */
class PathTooLongError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 414, severity: "error", message: "Path is too long.", ...options, reason: "length", target: "path", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the server fails to establish or maintain a required connection. */
class ServerConnectionError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "Server connection failed.", ...options, reason: "connection", target: "server", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a server-side input/output operation fails. */
class ServerInputOutputError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "Server I/O operation failed.", ...options, reason: "inputOutput", target: "server", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an unexpected internal server error occurs. */
class ServerInternalError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "Internal server error.", ...options, reason: "internal", target: "server", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a server operation exceeds the allowed time limit. */
class ServerTimeoutError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 504, severity: "error", message: "Server operation timed out.", ...options, reason: "timeout", target: "server", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a symbolic link loop is detected during path resolution. */
class SymlinkLoopError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 508, severity: "critical", message: "Symbolic link loop detected.", ...options, reason: "loop", target: "link", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when CPU usage reaches a critical level that may affect system stability. */
class SystemCriticalCpuUsageError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 507, severity: "critical", message: "Critical CPU usage detected.", ...options, reason: "hardware", target: "system", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the system runs out of disk space. */
class SystemOutOfDiskSpaceError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 507, severity: "critical", message: "System ran out of disk space.", ...options, reason: "hardware", target: "system", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the system runs out of available memory. */
class SystemOutOfMemoryError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 507, severity: "critical", message: "System ran out of memory.", ...options, reason: "hardware", target: "system", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the system is in read-only mode and write operations are not allowed. */
class SystemReadOnlyError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 503, severity: "error", message: "System is read-only.", ...options, reason: "permission", target: "system", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when the system exceeds the limit for simultaneously open files. */
class SystemTooManyFilesOpenError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 507, severity: "error", message: "Too many files are open.", ...options, reason: "connection", target: "system", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an authentication token has expired and is no longer valid. */
class TokenExpiredError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 401, severity: "error", message: "Authentication token expired.", ...options, reason: "expired", target: "token", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an authentication token is invalid or malformed. */
class TokenInvalidError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 401, severity: "error", message: "Authentication token is invalid.", ...options, reason: "invalid", target: "token", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an expected authentication token is missing from the request. */
class TokenMissingError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 401, severity: "error", message: "Authentication token is missing.", ...options, reason: "missing", target: "token", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when an unknown or unexpected error occurs. */
class UnknownError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 500, severity: "error", message: "An unknown error occurred.", ...options, reason: "unknown", target: "other", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a value violates a validation constraint (e.g., range, pattern, or rule). */
class ValidationConstraintViolationError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Validation constraint was violated.", ...options, reason: "format", target: "validation", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a value does not match the expected format during validation. */
class ValidationInvalidFormatError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Validation format is invalid.", ...options, reason: "format", target: "validation", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a required field is missing during validation. */
class ValidationMissingFieldError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Required field is missing.", ...options, reason: "missing", target: "validation", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a value contains unexpected whitespace. */
class ValueContainsWhitespaceError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Value contains whitespace.", ...options, reason: "format", target: "value", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a value is of the wrong data type. */
class ValueDataTypeError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Value has the wrong data type.", ...options, reason: "type", target: "value", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a value is empty or zero, but a valid value is required. */
class ValueEmptyOrZeroError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Value is empty or zero.", ...options, reason: "empty", target: "value", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a value does not match the expected format. */
class ValueFormatError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Value format is invalid.", ...options, reason: "format", target: "value", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Thrown when a value is outside the allowed range. */
class ValueOutOfRangeError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Value is out of range.", ...options, reason: "range", target: "value", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

/** Used to represent unexpected errors related to invalid or improperly formatted values. */
class ValueUnexpectedError extends CustomBaseError {
  constructor(options?: Omit<CustomAdditionalErrorDetails, 'reason' | 'target'>) {
    super({ code: 400, severity: "error", message: "Unexpected value error.", ...options, reason: "format", target: "value", isBuiltin: true } as RequiredPredefinedErrorDetails & CustomAdditionalErrorDetails);
  }
}

// Export custom error classes.
export {
  ApiInvalidRequestError,
  ApiMethodNotAllowedError,
  ApiNotFoundError,
  ApiRateLimitError,
  ApiVersionError,
  AssertionError,
  AuthForbiddenError,
  AuthPermissionError,
  AuthSessionExpiredError,
  AuthUnauthorizedError,
  DatabaseConnectionError,
  DatabaseDisconnectionError,
  DatabaseQueryError,
  DatabaseTimeoutError,
  DirectoryAlreadyExistsError,
  DirectoryCreationError,
  DirectoryDeletionError,
  DirectoryEmptyError,
  DirectoryExpectedError,
  DirectoryNotEmptyError,
  DirectoryNotFoundError,
  DirectoryPathFormatError,
  DirectoryPermissionError,
  FileAlreadyExistsError,
  FileCopyError,
  FileCreationError,
  FileDeletionError,
  FileEmptyError,
  FileExpectedError,
  FileExtensionError,
  FileNotFoundError,
  FilePathFormatError,
  FilePermissionError,
  FileSystemLimitError,
  FileUnreadableError,
  FileUnwritableError,
  LinkNotFoundError,
  NetworkAddressInUseError,
  NetworkConnectionError,
  NetworkHostUnreachableError,
  NetworkPortInUseError,
  ObjectPropertyMissingError,
  PathTooLongError,
  ServerConnectionError,
  ServerInputOutputError,
  ServerInternalError,
  ServerTimeoutError,
  SymlinkLoopError,
  SystemCriticalCpuUsageError,
  SystemOutOfDiskSpaceError,
  SystemOutOfMemoryError,
  SystemReadOnlyError,
  SystemTooManyFilesOpenError,
  TokenExpiredError,
  TokenInvalidError,
  TokenMissingError,
  UnknownError,
  ValidationConstraintViolationError,
  ValidationInvalidFormatError,
  ValidationMissingFieldError,
  ValueContainsWhitespaceError,
  ValueDataTypeError,
  ValueEmptyOrZeroError,
  ValueFormatError,
  ValueOutOfRangeError,
  ValueUnexpectedError,
};

// Export custom error generator function.
export {createCustomNamedError} from "./functions/createCustomNamedError.js";

// Export constants.
export {ERROR_TARGET_REASON_MAP} from "./data/constants/ERROR_TARGET_REASON_MAP.js";
export {SEVERITY} from "./data/constants/SEVERITY.js";

// Export: interfaces and types.
export type {CustomAdditionalErrorDetails} from "./types/CustomAdditionalErrorDetails.js";
export type {CustomBaseErrorOptions} from "./types/CustomBaseErrorOptions.js";
export type {DefaultErrorOptions} from "./types/DefaultErrorOptions.js";
export type {ErrorReason} from "./types/ErrorReason.js";
export type {ErrorTarget} from "./types/ErrorTarget.js";
export type {ErrorTargetReasonMap} from "./types/ErrorTargetReasonMap.js";
export type {RequiredPredefinedErrorDetails} from "./types/RequiredPredefinedErrorDetails.js";
export type {Severity} from "./types/Severity.js";